### ISSUE TITLE
Report formatting

### ISSUE THREAD

**Issue by AgonyAunt** [SayakMukhopadhyay/bgsbot#11]
Not sure what you have planned here, probably something you are alerady thinking about.

But basically tabular tables by system, eg:

System: Phekda
The Ancients of Mumu 29.5% Boom (Up 2%)
Perez Ring Brewery 21,3% None (Up 1%)
Independent Phekda Union 16.7% Civil Unrest (Down 3.2%)
etc...

**Comment by AgonyAunt** [comment]
And of course, reports by faction as well, similar to the above but by faction then system rather than system then faction.

**Comment by SayakMukhopadhyay** [comment]
This can be achieved using `@BGSBot systemstatus get Phekda` , Check the docs https://elitebgs.kodeblox.com/bgsbot/docs Under the section Using the Bot. Closing the issue. Feel free to reopen if required.
