### ISSUE TITLE
Time stamps for faction and system

### ISSUE THREAD

**Issue by CommanderTaken** [SayakMukhopadhyay/bgsbot#18]
There is a mismatch in the time stamp for the faction and system report.

If a faction is in system A and system B, and there is faction data from 1 hour ago from system A, then when the report is ran for system B, the time stamp is used for the factions from system A even if system B's data hasn't been updated for many hours.  
This creates out of date data (influence in system B) being reported as up to date (faction state from system A).

Keeping faction and system time stamps separate might be needed.

**Comment by SayakMukhopadhyay** [comment]
This is a difficult one. Currently faction update times are recorded once for a faction and not for each system. This is the reason why the update time for a faction is shown to be the latest irrespective of system. The change you are looking for is achievable but is going to be a bit difficult. I will keep this one open but cannot give an ETA.
