### ISSUE TITLE
BGSReport not allowing multiple faction monitoring

### ISSUE THREAD

**Issue by TornadoADG** [SayakMukhopadhyay/bgsbot#21]
Set a Primary Faction to be monitored and then set another faction but not primary, BGSReport failed to automatically run and failed to be called when asked for manually

**Comment by SayakMukhopadhyay** [comment]
You need to make sure that you are also monitoring systems where the faction in question is present. BGSReport is dependant on a system and its faction. Omitting either one will cause BGSReport to fail.

**Comment by TornadoADG** [comment]
Thank you for replying and apologies I realise that I didn’t explain it very well.

 

What we actually tried to do was monitor multiple systems not factions, but it only allows us to monitor one system.

 

Thanks

 

Andy

**Comment by SayakMukhopadhyay** [comment]
This shouldn't be the case. I am monitoring 3 systems in my own server. Can you join the Elite BGS Discord server (invite in the website)? I will look into this manually.

**Comment by TornadoADG** [comment]
Just joined Elite BGS on Discord as TornadoADG

 

Thanks

 

Andy

**Comment by SayakMukhopadhyay** [comment]
Issue solved in private conversation.
Outcome: BGSreport needs to have monitored factions and monitored systems which are present in each other.
