### ISSUE TITLE
BGS Bot in Discord has stopped responding

### ISSUE THREAD

**Issue by TornadoADG** [SayakMukhopadhyay/bgsbot#22]
The link with BGS Bot in our discord channel seems to have disconnected other than BGS Bot Help no other command elicits a response.

**Comment by SayakMukhopadhyay** [comment]
Was it working previously? If so, check if you have changed any property of a Discord role put on the bot. The bot needs to have write and embed permissions to work properly.

**Comment by TornadoADG** [comment]
Hi,

 

Yes it was, admittedly we tried to allow other users permission to run commands in the channel, without setting BGS Bot to allow them, so then permissions could be out of sync.

 

We don’t even get a message back from the bot when sending Hi

 

Permissions are set correctly as far as I can see.

 

Thanks

 

Andy

**Comment by TornadoADG** [comment]
Apologies, another admin had removed the permissions role from the Bot, now fixed.  Thanks
