### ISSUE TITLE
sort set not working

### ISSUE THREAD

**Issue by Tigir** [SayakMukhopadhyay/bgsbot#31]
Tried all four ways to set sorting, bot reported an error each time.
(Even did a c&p from the docs page.)

**Comment by SayakMukhopadhyay** [comment]
Some sort of example, preferable with screenshots would be nice as it is impossible to find a problem as it is.

**Comment by SayakMukhopadhyay** [comment]
Please comment on Github. Your email based reply didn't work as you intended.

**Comment by Tigir** [comment]
![image](https://user-images.githubusercontent.com/27549097/42270678-7530543e-7f4f-11e8-9cdb-55d8715a1f5a.png)

**Comment by SayakMukhopadhyay** [comment]
Ah! The docs seems to be having the wrong information. The correct command is like this
![image](https://user-images.githubusercontent.com/13748882/42270994-d7d46468-7f9f-11e8-9b7e-7d438ee16fce.png)
In the future, you can get the bot help by 
![image](https://user-images.githubusercontent.com/13748882/42271014-ecf74b6c-7f9f-11e8-8986-b7d8550d04fc.png)

**Comment by Tigir** [comment]
ok, so it's a bug in the docs, not the bot
thank you
