### ISSUE TITLE
paged bgsreport loses a faction over two pages.

### ISSUE THREAD

**Issue by Themadoll** [SayakMukhopadhyay/bgsbot#37]
I haven't tested this over more than 2 pages but iether the last faction on page one or the first faction on page two is lost when posted to the channel.
I have checked the database and all the factions exist in there.

**Comment by Themadoll** [comment]
I've added a line to the bgsreport.ts which I think fixes the bug.
`                for (let index = 0; index < fieldRecord.length; index++) {
                    if (fieldsInPage.length < 24) {
                        charactersPerPageCount += fieldRecord[index].fieldTitle.length + fieldRecord[index].fieldDescription.length;
                        console.log(fieldRecord[index].fieldTitle + " : " + fieldRecord[index].fieldDescription);
                    } else {
                        pagedFields.push(fieldsInPage);
                        fieldsInPage = [];
                        charactersPerPageCount = 0;
                    }
                    if (charactersPerPageCount < 5000) {
                        fieldsInPage.push(fieldRecord[index]);
                    } else {
                        pagedFields.push(fieldsInPage);
                        fieldsInPage = [];
                        charactersPerPageCount = 0;
						**index -= 1;**
                    }
                    if (index === fieldRecord.length - 1) {
                        pagedFields.push(fieldsInPage);
                        fieldsInPage = [];
                        charactersPerPageCount = 0;
                    }
                }
`

**Comment by SayakMukhopadhyay** [comment]
Closed by cdfff9c . Thanks for the quick fix!
