### ISSUE TITLE
BGSBot not accepting a role id

### ISSUE THREAD

**Issue by rodneywmcbride** [SayakMukhopadhyay/bgsbot#42]
Is there a limit to number of characters in a role name?

I created a role named BGSBot_Manager and when I enter \@BGSBot_Manager, I get <@somenumber>_manager. BGSBot will not accept the number when attempting to add a new admin role.

**Comment by SayakMukhopadhyay** [comment]
Could you provide a screenshot of the command and the error response?

**Comment by rodneywmcbride** [comment]
Below is a screenshot of the out from the \@BGSBot_Manager cmd and the error I get when attempting to use the role id.

![Capture](https://user-images.githubusercontent.com/33042509/54145791-0c18fc00-4405-11e9-8c37-f1133e0a30b6.PNG)

**Comment by SayakMukhopadhyay** [comment]
First of all there is no `@BGSBot_Manager` command. The procedure to add an admin role is detailed as such

> An admin role is able to execute all commands. Find which role you want to add as an admin role. You can add many roles as admin roles. Next you need to find the id of the admin role(s). To do that prepend the mention of your role with \. Eg. if your role is admin, you need to use \@admin to see the id. 

So, you need to identify a role on your server that you want to have admin perms on the bot. Then to get the id of that role, mention the role in the server adding a `\` before it. Then use the id with the `@bgsbot adminroles add` command. Hope that helps.

**Comment by rodneywmcbride** [comment]
No, BGSBot_Manager is the name of the role I created that I want to add as an adminrole.

The first entry you see in the screenshot is the output from \@BGSBot_Manager, the name of the role that I was trying to get the role id from.

**Comment by rodneywmcbride** [comment]
I just noticed that github is stripping the backslash off from my comment.

The cmd is <\@BGSBot_Manager>

**Comment by SayakMukhopadhyay** [comment]
Hmm...that's really weird. One thing for sure, it's not really an issue of bgsbot. Discord is having issues with giving our the id for the role. But I would like to help you out regardless. Could you join my server, temporarily even, so that I can easily assist you. Invite linked above.

**Comment by SayakMukhopadhyay** [comment]
Oh, I think I know the issue. Make sure that the bgsbot_manager role is mentionable. You won't be able to get the id of a role of its not set to mentionable. You can turn off mentions after getting the id.

**Comment by rodneywmcbride** [comment]
Yes, that I think that was it. I got the correct role id and the bgsbot adminroles add <role_id> worked perfectly.

Thanks for the quick responses on this.

Issue resolved.
