### ISSUE TITLE
Bot denying permissions

### ISSUE THREAD

**Issue by ADHDChief** [SayakMukhopadhyay/bgsbot#7]
I set the admin role but after that it says no one has permission to set up the bgs role or enter commands

**Comment by SayakMukhopadhyay** [comment]
Can you make sure you set up the admin role correctly? You can remove the admin role you set up using `remove` in place of `add`. BGS role can be set up only by the person having the admin role.

**Comment by ADHDChief** [comment]
I do have the admin role. Its not letting me set it after i set myself as the admin saying you dont have permissions
![screenshot_2017-11-02-00-41-11](https://user-images.githubusercontent.com/29551581/32310148-c4f92698-bf66-11e7-8c62-f103e6fccef0.png)

**Comment by SayakMukhopadhyay** [comment]
You are using wrong values for the role id. You should be using only the number.
`@BGSBot adminroles add 186...`
Try to remove the admin role and add them again. If you are facing any issues removing the admin role, tell me and I can remove them for you.

**Comment by ADHDChief** [comment]
Still refusing to follow commands
![screenshot_2017-11-02-05-36-48](https://user-images.githubusercontent.com/29551581/32319184-1112ffda-bf90-11e7-842a-a225cbee835e.png)

**Comment by SayakMukhopadhyay** [comment]
Hmm..as expected, since the bot already has the wrong admin role id, you are not getting authorised, Give me a couple of hours. I will fix it for you after returning home.

**Comment by ADHDChief** [comment]
I will after work

**Comment by SayakMukhopadhyay** [comment]
I have made a few changes in the code in #8 . Now users would not be able to add wrong guild ids. I am closing this issue. If you need any other assistance, feel free to join the EliteBGS discord server as mentioned here https://elitebgs.kodeblox.com/about
